name: Build TUI Version
on: workflow_dispatch # Запуск вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev pkg-config
      - name: Build
        run: cargo build --release --features tui
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: antumbra-tui-linux
          path: target/release/antumbra
